### ISSUE TITLE
could you share your model variants

### ISSUE THREAD

**Issue by ginger0106** [stanford-mast/INFaaS#1]
Hey thanks for the sharing codes, could you share your model variants?

**Comment by faromero** [comment]
Hi ginger0106,
Thank you for your interest in INFaaS!
We currently don't have our model-variants set up for public distribution, but we are hoping to get that done in the near future. However, we made heavy use of the publicly available pre-trained models from popular frameworks such as [PyTorch](https://pytorch.org/docs/stable/torchvision/models.html), [TensorFlow](https://github.com/tensorflow/models/tree/master/research/slim), and [Keras](https://keras.io/applications/), and you can do the same. You can freeze these models and profile them by using our scripts and following the instructions in our README. Finally, you can register them with INFaaS.
