### ISSUE TITLE
 What should I do if I want to deploy locally?

### ISSUE THREAD

**Issue by bedoom** [stanford-mast/INFaaS#10]
I am a first-year graduate student with limited knowledge of model serving. Currently, I can get a four-card GPU machine(I'm not sure I can get more😟). If I want to reproduce this paper, what should I do? If I can do it locally, I will share the results with you.🎇

**Comment by bedoom** [comment]
@qianl15

**Comment by qianl15** [comment]
Thanks for your interest in INFaaS! Both students who worked on this project have graduated, so this repo is not actively maintained. This repo currently contains scripts (such as [start_infaas.sh](https://github.com/stanford-mast/INFaaS/blob/main/start_infaas.sh) to run on AWS, but you may adjust them to run processes on your local machine. 

If you have a four-card GPU machine, you can try to treat each GPU as an independent "GPU worker" and use CPUs to run a "CPU worker", so you would potentially have 4 GPU-workers and 1 CPU-worker.

If you can run INFaaS it locally, you're welcome to contribute your code (not required).

Good luck!

**Comment by HigashikataZhangsuke** [comment]
@bedoom 
Hi bedoom, 

Did you find out how to run INFaaS on local machine eventually?

Thanks for your kind reply!
