### ISSUE TITLE
Question regarding model registration

### ISSUE THREAD

**Issue by arpangujarati** [stanford-mast/INFaaS#3]
Hi,

I am trying to setup INFaaS, and having problem with accessing the `infaas-sample-public` config database. Is the bucket still public?

Thanks,
Arpan

**Comment by qianl15** [comment]
Hi Arpan,

Thanks for bringing up the issue! Yes, the bucket is public. The access to the bucket should be fixed now. Would you try again?

Thanks,
Qian

**Comment by arpangujarati** [comment]
Thanks for fixing. The bucket is accessible now.

One more question.

I am following the model registration in the README example. I do not have a GPU instance yet, so working only with the CPU model. My model repository bucket  name is `infaasmodelrepo`. When I try to register `resnet50_tensorflow-cpu_4` using the suggested command in the README, I get an error, as follows:
```
ubuntu@ip-172-31-21-222:~/INFaaS/build/bin$ ./infaas_modelregistration resnet50_tensorflow-cpu_4.config infaas-sample-public/resnet50_tensorflow-cpu_4/
Model registration for resnet50_tensorflow-cpu_4... FAILED: Model not copied successfully. Model path likely invalid!
```

The `modelreg_server.log` contains the following messages:
```
[Redis Metadata]: Successfully connected
Server listening on 0.0.0.0:50053
[LOG]: Source infaas-sample-public/resnet50_tensorflow-cpu_4/
[LOG]: Destination infaasmodelrepo/resnet50_tensorflow-cpu_4/
[LOG]: Model path probably wrong...
ERROR: : No response body.
```

Note that for debugging purposes I have added two new lines in the `modelreg_server.cc` file:
```
std::cout << "[LOG]: Source " << complete_source << std::endl;
std::cout << "[LOG]: Destination " << complete_destination << std::endl;
```

However, despite the error, it seems that in my model repository `infaasmodelrepo` the following directory structure and file has been created: `infaasmodelrepo/resnet50_tensorflow-cpu_4/1/saved_model.pb`.

On the other hand, if I try the following command, the model registration is successful.
```
ubuntu@ip-172-31-21-222:~/INFaaS/build/bin$ ./infaas_modelregistration resnet50_tensorflow-cpu_4.config infaas-sample-public/
Model registration for resnet50_tensorflow-cpu_4... SUCCEEDED
```

In this case, my model repository `infaasmodelrepo` is updated as follows:
```
ubuntu@ip-172-31-21-222:~/INFaaS$ aws s3 ls s3://infaasmodelrepo
2020-04-17 03:19:04        195 resnet50_tensorflow-cpu_4
```

and the `modelreg_server.log` contains the following messages:
```
[Redis Metadata]: Successfully connected
Server listening on 0.0.0.0:50053
[LOG]: Source infaas-sample-public/
[LOG]: Destination infaasmodelrepo/resnet50_tensorflow-cpu_4/
[LOG]: Successfully copied
[LOG]: Successfully registered resnet50_tensorflow-cpu_4 (Parent: resnet50)
[LOG]: Calculated slope: 186.396; Calculated intercept: 57.8378
=================================================
```

Could you help me understand which one is the right approach for model registration?

Thanks,
Arpan

**Comment by faromero** [comment]
Hi @arpangujarati 
Thank you for trying out INFaaS!
The first way you ran the model registration is the correct one (i.e., the README way). I checked the model registration server, and it turns out that it was correctly registering your model, but the HeadObject cli was for some reason not finding the model's object in INFaaS' bucket (so it thought it failed). I updated the way it checks to verify the model was registered properly, so you can try pulling, rebuilding, and re-registering the model to see if it was successful. Let me know if you have further issues.

Franky

**Comment by arpangujarati** [comment]
Thanks a lot Franky. The commit works. I am able to successfully run the online query over a CPU.
