### ISSUE TITLE
Couldn't copy EC2 AMI

### ISSUE THREAD

**Issue by ruizehung** [stanford-mast/INFaaS#8]
I was trying to copy the public AMI (ami-036de08e2e59b4abc) mentioned in README in us-west-2, but I got 
```
Failed to copy ami-036de08e2e59b4abc
You do not have permission to access the storage of this ami
```
See the screenshot below:
<img width="884" alt="image" src="https://user-images.githubusercontent.com/35753861/216850430-e3da8170-f66c-4b76-aee3-fff8d8fb46fc.png">

**Comment by Lingkar** [comment]
Hi, @ruizehung if you wish you can give my AMI a try. It is on eu-central-1.
Let me know if you succeeded, as I will be taking it offline in the upcoming days/week
ami-0c3adce266b668f8e

**Comment by ruizehung** [comment]
Actually, I realized that I can just launch a machine from `ami-036de08e2e59b4abc` and create an image and copy that to my region. But anyway thanks @Lingkar !

**Comment by HigashikataZhangsuke** [comment]
@ruizehung @Lingkar 

Hi Rui&Lingkar!

Do you still keep a copy of this AMI with your side? Unfortunatelly, the original AMI seems expired. Just wanna to see if I could get an AMI from you guys to run INFaaS quickly.

Thank you for your kind reply!

**Comment by Lingkar** [comment]
@HigashikataZhangsuke I am afraid not, sorry.
